name: Publish @screenside/ui

on: workflow_dispatch

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.1

      - name: Install Dependencies
        run: pnpm install

      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release:ui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
